# site settings
title: MyTravelCare
subtitle: by Evocare Srl
email: evocare.mytravelcare@gmail.com
# description: A responsive site template designed by HTML5 Up<br /> and released under the Creative Commons.
description: Al sicuro con la tua salute anche quando non sei a casa
long_description: >
  Evocare aiuta i pazienti a superare le barriere della Salute. Crediamo che migliorare la qualità, l’accessibilità e l’efficacia del sistema rappresenti l’evoluzione essenziale della Salute. Evocare è una startup innovativa fondata sull’esperienza di un gruppo dinamico di persone. Il nostro team è unico: combina la competenza tecnologica e manageriale con la sensibilità e la conoscenza in campo sanitario.
baseurl: "/" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
street_address: Via Corso Magenta, 56
city: Milano
state: MI
zip_code: 20123
country: Italy
phone: (+39) 035 3068272 

# social settings
500px_url:
facebook_url:
github_url:
gitlab_url: 
googleplus_url: 
instagram_url: 
linkedin_url: 
pinterest_url:
slack_url:
twitter_url: 

# build settings
markdown: kramdown

sass:
  style: compressed

collections_dir: collections

collections:
  - functions